import Link from 'next/link'

const workflow = ['Forecast', 'Prepare', 'Monitor', 'Adapt', 'Reduce waste']
const features = [
  ['01', 'Demand forecasting', 'Turn live order signals into a confident prep plan before the rush reaches the pass.'],
  ['02', 'Progressive preparation', 'Prepare in intelligent batches, keeping freshness high while staying ready for demand.'],
  ['03', 'Waste intelligence', 'See where margin is leaking and make every avoided plate measurable.'],
]

export default function Landing() {
  return <main className="landing">
    <nav className="landing-nav"><Link href="/" className="landing-logo">Plate<span>IQ</span></Link><div><a href="#product">Product</a><a href="#how">How it works</a><Link href="/app">Live demo</Link><Link href="/login" className="primary-button">Sign in <span>↗</span></Link></div></nav>
    <section className="hero">
      <div className="hero-copy"><div className="eyebrow">INTELLIGENT KITCHEN OPERATIONS <span className="eyebrow-dot" /></div><h1>Make every <em>plate</em> count.</h1><p>PlateIQ gives restaurant teams a clear, live view of what to prepare, when to prepare it, and how to waste less.</p><div className="hero-actions"><Link href="/app" className="primary-button">Explore live demo <span>↗</span></Link><a href="#how">See how it works <span>↓</span></a></div><div className="hero-proof"><span className="avatar-stack"><i>J</i><i>H</i><i>+</i></span><span>Built for the pace of<br/><strong>modern kitchens</strong></span></div></div>
      <div className="hero-visual"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-card"><div className="hero-card-top"><span className="section-kicker">Live demand monitor</span><span className="status-badge">● AI system live</span></div><h2>Orders are arriving faster than forecast</h2><div className="hero-stat"><strong>1,248</strong><span>meals projected</span><b>+14.2%</b></div><div className="mini-chart">{[35,50,42,70,57,84,72,100].map((height, i) => <i key={i} style={{height: `${height}%`}} />)}</div><div className="food-frame"><img src="/chicken-biryani.png" alt="A plated chicken biryani dish"/><span>Freshness window<br/><strong>18 min</strong></span></div><div className="floating-note"><span>↑</span><div><strong>Prep window optimized</strong><small>Next batch in 18 min</small></div></div></div></div>
    </section>
    <section className="signal-strip"><span>ONE OPERATING PICTURE</span><div>{workflow.map((item, i) => <span key={item}><strong>{item}</strong>{i < workflow.length - 1 && <i>→</i>}</span>)}</div><span>LESS GUESSWORK</span></section>
    <section id="product" className="feature-section"><div className="feature-intro"><div className="eyebrow">A BETTER WAY TO RUN SERVICE</div><h2>Your kitchen has a rhythm. <em>PlateIQ listens.</em></h2><p>Connect the decisions your team makes every shift — from first prep to final plate — in one calm, intelligent workspace.</p></div><div className="feature-list">{features.map(([number, title, copy]) => <article className="feature-row" key={title}><span className="feature-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div><span className="feature-arrow">↗</span></article>)}</div></section>
    <section id="how" className="how"><div className="how-heading"><div className="eyebrow">HOW PLATEIQ WORKS</div><h2>From uncertainty to a smarter kitchen.</h2></div><div className="steps">{workflow.map((item, i) => <div className="step" key={item}><span>0{i + 1}</span><strong>{item}</strong><p>Make the next decision with confidence.</p></div>)}</div></section>
    <section className="product-preview"><div><div className="eyebrow">THE OPERATING PICTURE</div><h2>Clarity for the <em>rush hour.</em></h2><p>One view for demand, kitchen capacity, food safety, and waste risk — so your team can act instead of react.</p><Link href="/app" className="outline-button">Open the workspace <span>↗</span></Link></div><div className="preview-window"><div className="preview-top"><span>Overview</span><span>● Live system</span></div><div className="preview-body"><div className="preview-metric"><small>Today&apos;s demand</small><strong>1,248</strong><b>+14.2%</b></div><div className="preview-metric"><small>Prepared so far</small><strong>862</strong><b>69.1%</b></div><div className="preview-chart">{[30,45,38,58,52,75,68,90,83].map((height, i) => <i key={i} style={{height: `${height}%`}} />)}</div></div></div></section>
    <section className="landing-cta"><div className="eyebrow">READY WHEN YOU ARE</div><h2>Turn uncertainty into<br/><em>smarter kitchen decisions.</em></h2><Link href="/app" className="primary-button">Open PlateIQ <span>↗</span></Link></section>
    <footer className="landing-footer"><Link href="/" className="landing-logo">Plate<span>IQ</span></Link><span>Kitchen intelligence, in real time.</span><Link href="/login">Sign in ↗</Link></footer>
  </main>
}
