'use client'
import { useState } from 'react'
import { ArrowRight, Check, CloudRain, Sparkles } from 'lucide-react'
import { usePlateIQ } from './plateiq-state'

export function WhatIfPage(){
  const {state,dispatch}=usePlateIQ(); const [change,setChange]=useState(state.scenario.customerChange)
  const simulated=Math.round(state.metrics.demand*(1+change/100)*(state.scenario.weather==='Heavy Rain'?.88:state.scenario.weather==='Rain'?.94:state.scenario.weather==='Cloudy'?.98:1)*(state.scenario.promotion?1.1:1))
  const preparation=Math.max(0,Math.ceil((simulated-state.demo.prepared)/30)*30)
  return <div className="page-body"><div className="page-heading"><div><div className="eyebrow">PLATEIQ OPERATIONS <span className="separator">•</span> DECISION SIMULATOR</div><h1>What happens if tomorrow changes?</h1><p>Model demand shifts before they reach the kitchen.</p></div></div><div className="panel simulator"><div><div className="section-kicker"><CloudRain/> Scenario controls</div><h2>Change the conditions</h2><label>Expected customer change <strong>{change>0?'+':''}{change}%</strong></label><input type="range" min={-30} max={50} value={change} onChange={e=>setChange(Number(e.target.value))}/><div className="scenario-options"><button className={state.scenario.weather==='Clear'?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{weather:'Clear',customerChange:change}})}>Clear</button><button className={state.scenario.weather==='Cloudy'?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{weather:'Cloudy',customerChange:change}})}>Cloudy</button><button className={state.scenario.weather==='Rain'?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{weather:'Rain',customerChange:change}})}>Rain</button><button className={state.scenario.weather==='Heavy Rain'?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{weather:'Heavy Rain',customerChange:change}})}>Heavy rain</button></div><div className="scenario-options"><button className={state.scenario.holiday==='None'?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{holiday:'None'}})}>No holiday</button><button className={state.scenario.holiday==='High'?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{holiday:'High'}})}>High holiday</button><button className={state.scenario.localEvent==='High'?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{localEvent:'High'}})}>Large event</button><button className={state.scenario.promotion?'active':''} onClick={()=>dispatch({type:'scenario',scenario:{promotion:!state.scenario.promotion}})}>Promotion active</button></div></div><div className="comparison"><span>Current</span><strong>{state.metrics.demand.toLocaleString('en-IN')}</strong><ArrowRight/><span>Simulated</span><strong>{simulated.toLocaleString('en-IN')}</strong></div></div><section className="panel"><div className="section-kicker"><Sparkles/> Applied plan preview</div><div className="response-grid"><div><span>Demand</span><strong>{simulated}</strong></div><div><span>Preparation</span><strong>+{preparation}</strong></div><div><span>Stockout risk</span><strong>{state.inventory.filter(i=>i.status!=='Healthy').length}</strong></div><div><span>Waste impact</span><strong>{change>0?'+':'−'}{Math.abs(change)}%</strong></div></div><button className="primary-button" onClick={()=>dispatch({type:'apply-plan'})}>Apply plan <Check/></button></section></div>
}

export function CopilotPage(){const {state,dispatch}=usePlateIQ(); const [question,setQuestion]=useState('How much biryani should we prepare?'); const dish=state.dishes.find(d=>d.id==='biryani'); const forecast=state.forecasts.find(f=>f.dishId==='biryani'); const questions=['How much biryani should we prepare?','What should the kitchen prepare next?','Which ingredients need attention?','How much can we save this month?']; const answer=question.startsWith('Which')?`${state.inventory.filter(i=>i.status!=='Healthy').length} ingredients need attention.`:question.startsWith('How much can')?`Current modeled savings are ₹${state.metrics.savings.toLocaleString('en-IN')} per month.`:question.startsWith('What should')?`Start batch #${state.demo.batch.number} when the next velocity checkpoint is reached.`:`Prepare ${state.demo.projectedDemand} plates within the ${forecast?.lowerBound}–${forecast?.upperBound} range. ${state.demo.prepared} are prepared; the next batch is +${dish?.nextBatch||30} plates.`; return <div className="page-body"><div className="page-heading"><div><div className="eyebrow">PLATEIQ OPERATIONS <span className="separator">•</span> OPERATIONAL COPILOT</div><h1>Ask PlateIQ</h1><p>Turn the current operating state into the next kitchen decision.</p></div></div><section className="copilot-grid"><div className="panel suggested"><div className="section-kicker"><Sparkles/> Suggested questions</div>{questions.map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}<ArrowRight/></button>)}</div><div className="panel copilot-response"><div className="section-kicker"><Sparkles/> Operational response</div><h2>{question}</h2><div className="response-grid"><div><span>Current forecast</span><strong>{forecast?.forecast||state.demo.forecast}</strong></div><div><span>Actual orders</span><strong>{state.demo.orders}</strong></div><div><span>Projected range</span><strong>{state.demo.lowerBound}–{state.demo.upperBound}</strong></div><div><span>Confidence</span><strong>{state.demo.confidence}%</strong></div></div><p><strong>Reason:</strong> {answer}</p><button className="primary-button" onClick={()=>dispatch({type:'batch'})}>{state.demo.batch.status==='Recommended'?`Start Batch #${state.demo.batch.number}`:state.demo.batch.status}</button></div></section></div>}

export function SettingsPage(){const {dispatch}=usePlateIQ();return <div className="page-body"><div className="page-heading"><div><div className="eyebrow">PLATEIQ OPERATIONS <span className="separator">•</span> WORKSPACE</div><h1>Settings</h1><p>Configure the deterministic demo workspace and reset operational state.</p></div></div><div className="settings-grid"><section className="panel settings-card"><h2>Demo environment</h2><p>PlateIQ uses a fixed Hyderabad lunch-service environment for this workspace.</p><div className="setting-row"><span>Restaurant</span><strong>Spice Route Kitchen</strong></div><div className="setting-row"><span>Currency</span><strong>INR</strong></div><div className="setting-row"><span>Timezone</span><strong>Asia/Kolkata</strong></div></section><section className="panel settings-card"><h2>Reset application data</h2><p>Restore orders, forecasts, batches, inventory, waste, alerts, notifications, events, and scenario inputs to the initial baseline.</p><button className="outline-button" onClick={()=>dispatch({type:'reset-data'})}>Reset application data</button></section></div></div>}
