'use client'
import { createContext, useContext, useEffect, useMemo, useReducer } from 'react'
import type { PlateIQAction, PlateIQState, BatchStatus } from '@/lib/types'
import { restaurant, dishes, inventory, stations, alerts, scenario, waste } from '@/lib/mock-data'
import { getDemoMetrics } from '@/lib/demo-engine'
import { buildForecast } from '@/lib/forecasting'
import { consumeForBatch, receiveStock } from '@/lib/inventory-engine'
import { recalculateWaste, wasteSummary } from '@/lib/waste-engine'
const now='2025-06-24T12:45:00+05:30'
const initialBatch={id:'biryani-2',dishId:'biryani',number:2,quantity:30,status:'Recommended' as BatchStatus,createdAt:now,updatedAt:now}
export const initialState:PlateIQState={restaurant,dishes,forecasts:dishes.map(d=>({id:`forecast-${d.id}`,dishId:d.id,period:'Lunch',forecast:d.forecast,lowerBound:d.lowerBound,upperBound:d.upperBound,confidence:d.confidence,actual:d.actualOrders})),batches:[initialBatch],stations,inventory,waste,alerts,notifications:[],recommendations:[{id:'rec-1',title:'Start preparation batch #2',description:'Biryani is tracking above the initial baseline. Prepare +30 plates.',actionLabel:'Start Batch #2',confidence:91,dishId:'biryani'}],events:[],scenario,demo:{running:false,step:6,speed:1,orders:92,ordersPerMinute:7.7,baselineVelocity:8,projectedDemand:122,prepared:1010,kitchenCapacity:84,forecast:115,lowerBound:108,upperBound:123,confidence:91,status:'Adjusting',batch:initialBatch,showReason:false,dismissedAlertIds:[],scenario},metrics:{demand:1248,prepared:1010,wasteKg:34.6,wasteCost:4820,forecastAccuracy:91.8,savings:18420}}
function event(state:PlateIQState,type:string,title:string,description:string,href:string='/app'){const id=`event-${state.events.length+1}`;return {id,timestamp:'12:46 PM',type,title,description,severity:'info' as const,relatedEntity:href}}
function reducer(state:PlateIQState,action:PlateIQAction):PlateIQState{
 switch(action.type){
  case'hydrate':return action.state
  case'toggle':return {...state,demo:{...state.demo,running:!state.demo.running}}
  case'speed':return {...state,demo:{...state.demo,speed:action.value}}
  case'reset':return {...state,demo:{...initialState.demo,running:false}}
  case'reset-data':return initialState
  case'reason':return {...state,demo:{...state.demo,showReason:action.value}}
  case'dismiss-alert':return {...state,alerts:state.alerts.map(a=>a.id===action.alertId?{...a,dismissed:true}:a),demo:{...state.demo,dismissedAlertIds:[...state.demo.dismissedAlertIds,action.alertId]}}
  case'read-notifications':return {...state,notifications:state.notifications.map(n=>({...n,read:true}))}
  case'read-notification':return {...state,notifications:state.notifications.map(n=>n.id===action.notificationId?{...n,read:true}:n)}
  case'scenario':{const next={...state.scenario,...action.scenario};return {...state,scenario:next,demo:{...state.demo,scenario:next},events:[event(state,'SCENARIO_CHANGED','Scenario changed','Forecast inputs were updated.','/app/what-if'),...state.events]}}
  case'apply-plan':{const prepared=state.demo.prepared+30;const nextWaste=recalculateWaste(state.waste,state.dishes,prepared);const summary=wasteSummary(nextWaste);return {...state,waste:nextWaste,demo:{...state.demo,prepared},metrics:{...state.metrics,prepared,wasteKg:summary.wasteKg,wasteCost:summary.wasteCost},events:[event(state,'PLAN_APPLIED','Preparation plan applied','Batch recommendation added to the kitchen plan.','/app/kitchen-planner'),...state.events],notifications:[{id:`notification-${Date.now()}`,title:'Plan applied',description:'The kitchen preparation plan was updated.',href:'/app/kitchen-planner',read:false,createdAt:now},...state.notifications]}}
  case'receive-stock':return {...state,inventory:state.inventory.map(i=>i.id===action.itemId?receiveStock(i,action.amount):i),events:[event(state,'INVENTORY_UPDATED','Delivery received','Inventory levels were recalculated.','/app/inventory'),...state.events]}
  case'adjust-stock':return {...state,inventory:state.inventory.map(i=>i.id===action.itemId?receiveStock(i,action.amount):i)}
  case'mark-ordered':return {...state,notifications:[{id:`notification-${Date.now()}`,title:'Reorder placed',description:`${state.inventory.find(i=>i.id===action.itemId)?.name||'Ingredient'} marked as ordered.`,href:'/app/inventory',read:false,createdAt:now},...state.notifications]}
  case'batch':{const id=action.batchId||state.demo.batch.id;const current=state.batches.find(b=>b.id===id)||state.demo.batch;const nextStatus=current.status==='Recommended'?'In Preparation':current.status==='In Preparation'?'Ready':'Completed';const started=nextStatus==='In Preparation';const prepared=started?state.demo.prepared+current.quantity:state.demo.prepared;const nextInventory=started?consumeForBatch(state.inventory,state.dishes.find(d=>d.id===current.dishId)!,current.quantity):state.inventory;const e=event(state,'BATCH_'+nextStatus.toUpperCase().replace(' ','_'),`Batch #${current.number} ${nextStatus.toLowerCase()}`,'Kitchen plan updated from shared operational state.','/app/live-operations');return {...state,batches:state.batches.map(b=>b.id===id?{...b,status:nextStatus,updatedAt:now}:b),inventory:nextInventory,demo:{...state.demo,prepared,batch:{...current,status:nextStatus}},metrics:{...state.metrics,prepared},events:[e,...state.events],notifications:[{id:`notification-${Date.now()}`,title:`Batch #${current.number} ${nextStatus}`,description:'Kitchen, inventory, and dashboard state updated.',href:'/app/kitchen-planner',read:false,createdAt:now},...state.notifications]}}
  case'batch-status':return {...state,batches:state.batches.map(b=>b.id===action.batchId?{...b,status:action.status,updatedAt:now}:b)}
  case'tick':{const step=Math.min(8,state.demo.step+1);const m=getDemoMetrics(step);const forecast=buildForecast(state.dishes[0],m.orders,state.scenario);const isSurge=m.status==='Surge'&&!state.alerts.some(a=>a.id==='surge-live');const nextAlerts=isSurge?[...state.alerts,{id:'surge-live',title:'Demand Surge Detected',description:'Chicken Biryani demand is accelerating. Start preparation batch #2.',severity:'warning' as const,dismissed:false,relatedEntity:'biryani'}]:state.alerts;const e=event(state,'FORECAST_UPDATED','Forecast recalculated',`Projected demand updated to ${forecast.projectedDemand} plates.`,'/app/demand-forecast');return {...state,alerts:nextAlerts,events:[e,...state.events],notifications:isSurge?[{id:`notification-${Date.now()}`,title:'Demand surge detected',description:'PlateIQ recommends starting the next biryani batch.',href:'/app',read:false,createdAt:now},...state.notifications]:state.notifications,forecasts:state.forecasts.map(f=>f.dishId==='biryani'?{...f,forecast:forecast.forecast,lowerBound:forecast.lowerBound,upperBound:forecast.upperBound,confidence:forecast.confidence,actual:m.orders}:f),demo:{...state.demo,...m,status:m.status as 'Monitoring'|'Adjusting'|'Surge',step,forecast:forecast.forecast,lowerBound:forecast.lowerBound,upperBound:forecast.upperBound,confidence:forecast.confidence,projectedDemand:forecast.projectedDemand,batch:{...state.demo.batch}},metrics:{...state.metrics,demand:Math.round(state.metrics.demand+(m.orders-state.demo.orders)*1.4),prepared:m.prepared}}}
  default:return state
 }
}
const Ctx=createContext<{state:PlateIQState;dispatch:React.Dispatch<PlateIQAction>}|null>(null)
export function PlateIQProvider({children}:{children:React.ReactNode}){const [state,dispatch]=useReducer(reducer,initialState);useEffect(()=>{try{const saved=localStorage.getItem('plateiq-state');if(saved)dispatch({type:'hydrate',state:JSON.parse(saved) as PlateIQState})}catch{}},[]);useEffect(()=>{try{localStorage.setItem('plateiq-state',JSON.stringify(state))}catch{}},[state]);return <Ctx.Provider value={{state,dispatch}}>{children}</Ctx.Provider>}
export function usePlateIQ(){const value=useContext(Ctx);if(!value)throw new Error('usePlateIQ must be used within PlateIQProvider');return value}
export const navItems=[['Overview','/app'],['Live Operations','/app/live-operations'],['Kitchen Planner','/app/kitchen-planner'],['Demand Forecast','/app/demand-forecast'],['Inventory','/app/inventory'],['Waste Intelligence','/app/waste-intelligence'],['What-If Simulator','/app/what-if'],['Analytics','/app/analytics'],['AI Copilot','/app/copilot']] as const
export function usePlateIQMetrics(){const {state}=usePlateIQ();return useMemo(()=>({demand:state.metrics.demand,prepared:state.demo.prepared,waste:`${state.metrics.wasteKg.toFixed(1)} kg`,wasteCost:`₹${state.metrics.wasteCost.toLocaleString('en-IN')}`,accuracy:`${state.metrics.forecastAccuracy.toFixed(1)}%`,orders:state.demo.orders,projected:state.demo.projectedDemand,unread:state.notifications.filter(n=>!n.read).length,capacity:state.demo.kitchenCapacity}),[state])}
