'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Activity, Bell, ChevronDown, CloudRain, Gauge, LayoutDashboard, Leaf, Menu, Package, Settings2, Sparkles, ClipboardList, X, Zap } from 'lucide-react'
import { navItems, usePlateIQ } from './plateiq-state'
const icons=[LayoutDashboard,Activity,ClipboardList,Gauge,Package,Leaf,CloudRain,Sparkles,Sparkles]
export function AppShell({children}:{children:React.ReactNode}) { const path=usePathname(); const {state,dispatch}=usePlateIQ(); const [open,setOpen]=React.useState(false); const [notificationsOpen,setNotificationsOpen]=React.useState(false); return <main className="app-shell"><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark"><Leaf /></div><span>Plate<span>IQ</span></span><button className="mobile-close" onClick={()=>setOpen(false)} aria-label="Close menu"><X /></button></div><div className="restaurant-switch"><div className="restaurant-avatar">JH</div><div><strong>Jubilee Hills</strong><small>Hyderabad, India</small></div><ChevronDown /></div><nav>{navItems.map(([label,href],i)=>{const Icon=icons[i]; return <Link href={href} key={label} className={`nav-item ${path===href?'active':''}`} onClick={()=>setOpen(false)}><Icon />{label}{label==='Live Operations'&&<span className="live-pill">LIVE</span>}{label==='AI Copilot'&&<span className="new-pill">NEW</span>}</Link>})}</nav><div className="sidebar-bottom"><Link href="/app/settings" className={`nav-item ${path==='/app/settings'?'active':''}`}><Settings2 />Settings</Link><div className="profile"><div className="profile-avatar">AM</div><div><strong>Arjun Mehta</strong><small>Restaurant manager</small></div></div></div></aside><section className="content"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu /></button><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>{navItems.find(([,href])=>href===path)?.[0]||'Overview'}</strong></div><div className="top-actions"><div className="system-live"><span /> AI system live</div><button className="icon-button" aria-label="Notifications" onClick={()=>setNotificationsOpen(v=>!v)}><Bell />{state.notifications.filter(n=>!n.read).length>0&&<i>{state.notifications.filter(n=>!n.read).length}</i>}</button>{notificationsOpen&&<div className="notification-panel"><div className="notification-head"><strong>Notifications</strong><button onClick={()=>dispatch({type:'read-notifications'})}>Mark all read</button></div>{state.notifications.length===0?<p>No new operational notifications.</p>:state.notifications.slice(0,5).map(n=><Link key={n.id} href={n.href} onClick={()=>{dispatch({type:'read-notification',notificationId:n.id});setNotificationsOpen(false)}} className={`notification-item ${n.read?'read':''}`}><strong>{n.title}</strong><span>{n.description}</span></Link>)}</div>}<div className="demo-switch"><span>Demo mode</span><DemoToggle /></div><div className="top-avatar">AM</div></div></header>{children}</section></main> }
function DemoToggle(){const {state,dispatch}=usePlateIQ(); return <button className={state.demo.running?'on':''} onClick={()=>dispatch({type:'toggle'})} aria-label="Toggle demo mode"><b /></button>}
import React from 'react'
