import type { Dish, SimulationScenario } from './types'
export function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value))}
export function calculateForecast(dish:Dish,orders:number,scenario:SimulationScenario){const velocityAdjustment=clamp((orders-60)*.16,-8,18);const weather=scenario.weather==='Heavy Rain'?.9:scenario.weather==='Rain'?.96:scenario.weather==='Cloudy'?.98:1;const event=scenario.localEvent==='High'?1.12:scenario.localEvent==='Medium'?1.05:1;const holiday=scenario.holiday==='High'?1.16:scenario.holiday==='Medium'?1.08:scenario.holiday==='Low'?1.03:1;const promo=scenario.promotion?1.1:1;return Math.round((dish.forecast+velocityAdjustment)*weather*event*holiday*promo)}
export function predictionRange(forecast:number,confidence:number){const spread=Math.max(4,Math.round(forecast*(1-confidence/100)*.7));return {lowerBound:forecast-spread,upperBound:forecast+spread}}
export function preparationRecommendation(forecast:number,prepared:number,batchSize:number){return Math.max(0,Math.ceil((forecast-prepared)/batchSize)*batchSize)}
export function calculateCapacity(prepared:number,forecast:number){return clamp(Math.round((prepared/Math.max(forecast,1))*100),0,100)}
export function calculateWaste(prepared:number,consumed:number,spoilageKg:number){const overproduction=Math.max(0,prepared-consumed);const wasteKg=Number((spoilageKg+overproduction*.045).toFixed(1));return {overproduction,wasteKg,wasteCost:Math.round(wasteKg*150)}}
export function scenarioDemand(current:number,scenario:SimulationScenario){const weather=scenario.weather==='Heavy Rain'?.88:scenario.weather==='Rain'?.94:scenario.weather==='Cloudy'?.98:1;const levels={None:1,Low:1.03,Medium:1.08,High:1.16};return Math.round(current*(1+scenario.customerChange/100)*weather*levels[scenario.holiday]*levels[scenario.localEvent]*(scenario.promotion?1.1:1))}
export function stockoutRisk(daysLeft:number){return clamp(Math.round((2-daysLeft)*18),0,98)}
