import type { Dish, SimulationScenario } from './types'
export function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value))}
export function scenarioMultiplier(scenario:SimulationScenario){const weather=scenario.weather==='Heavy Rain'?.88:scenario.weather==='Rain'?.94:scenario.weather==='Cloudy'?.98:1;const levels={None:1,Low:1.03,Medium:1.08,High:1.16};return (1+scenario.customerChange/100)*weather*levels[scenario.holiday]*levels[scenario.localEvent]*(scenario.promotion?1.1:1)}
export function calculateForecast(dish:Dish,orders:number,scenario:SimulationScenario,baselineForecast=dish.forecast){const velocityAdjustment=clamp((orders-60)*.16,-8,18);return Math.max(0,Math.round((baselineForecast+velocityAdjustment)*scenarioMultiplier(scenario)))}
export function predictionRange(forecast:number,confidence:number){const spread=Math.max(4,Math.round(forecast*(1-confidence/100)*.7));return {lowerBound:Math.max(0,forecast-spread),upperBound:Math.max(forecast,forecast+spread)}}
export function preparationRecommendation(demand:number,prepared:number,batchSize:number,kitchenCapacity=100,leadTimeMinutes=0){if(demand<=prepared||batchSize<=0||kitchenCapacity<=0)return 0;const capacityFactor=clamp(kitchenCapacity/100,.5,1);const leadTimeBuffer=demand*Math.min(.25,leadTimeMinutes/240);const target=demand/capacityFactor+leadTimeBuffer;return Math.max(0,Math.ceil((target-prepared)/batchSize)*batchSize)}
export function calculateCapacity(prepared:number,forecast:number){return clamp(Math.round((prepared/Math.max(forecast,1))*100),0,100)}
export function calculateWaste(prepared:number,consumed:number,spoilageKg:number){const overproduction=Math.max(0,prepared-consumed);const wasteKg=Number((spoilageKg+overproduction*.045).toFixed(1));return {overproduction,wasteKg,wasteCost:Math.round(wasteKg*150)}}
export function scenarioDemand(current:number,scenario:SimulationScenario){return Math.max(0,Math.round(current*scenarioMultiplier(scenario)))}
export function stockoutRisk(daysLeft:number){return clamp(Math.round((2-daysLeft)*18),0,98)}
