import type { Alert, Dish, InventoryItem, KitchenStation, Restaurant, SimulationScenario, WasteRecord } from './types'
export const restaurant:Restaurant={id:'jubilee-hills',name:'Jubilee Hills Restaurant',city:'Hyderabad',country:'India',timezone:'Asia/Kolkata',currency:'₹'}
export const dishes:Dish[]=[
{id:'biryani',name:'Chicken Biryani',category:'Mains',forecast:126,lowerBound:118,upperBound:126,confidence:91,actualOrders:92,prepared:60,initialBatch:60,nextBatch:30,batchSize:30,leadTimeMinutes:18,status:'Batch Recommended',wasteKg:8.4,wasteCost:1260,ingredients:{Chicken:8,Rice:5,Yogurt:2,Onions:2.5}},
{id:'paneer',name:'Paneer Curry',category:'Mains',forecast:82,lowerBound:76,upperBound:88,confidence:94,actualOrders:65,prepared:70,initialBatch:70,nextBatch:20,batchSize:20,leadTimeMinutes:15,status:'On Track',wasteKg:5.1,wasteCost:765,ingredients:{Paneer:5,Tomatoes:3,Onions:1.5}},
{id:'rice',name:'Jeera Rice',category:'Sides',forecast:140,lowerBound:132,upperBound:148,confidence:96,actualOrders:112,prepared:120,initialBatch:120,nextBatch:20,batchSize:20,leadTimeMinutes:12,status:'Preparing',wasteKg:4.7,wasteCost:470,ingredients:{Rice:8,Spices:0.4}},
{id:'dal',name:'Dal Tadka',category:'Mains',forecast:74,lowerBound:68,upperBound:80,confidence:93,actualOrders:58,prepared:62,initialBatch:62,nextBatch:15,batchSize:15,leadTimeMinutes:14,status:'On Track',wasteKg:2.8,wasteCost:350,ingredients:{Lentils:4,Tomatoes:2}},
{id:'naan',name:'Naan',category:'Breads',forecast:188,lowerBound:175,upperBound:202,confidence:89,actualOrders:141,prepared:150,initialBatch:150,nextBatch:30,batchSize:30,leadTimeMinutes:8,status:'On Track',wasteKg:3.6,wasteCost:288,ingredients:{Flour:10,Butter:1.5}},
]
export const inventory:InventoryItem[]=[{id:'chicken',name:'Chicken',unit:'kg',currentStock:38,reorderPoint:18,dailyUsage:14,unitCost:260,status:'Healthy',daysLeft:2.7,trend:'Falling'},{id:'rice',name:'Basmati rice',unit:'kg',currentStock:26,reorderPoint:14,dailyUsage:9,status:'Healthy',unitCost:110,daysLeft:2.9,trend:'Falling'},{id:'tomatoes',name:'Tomatoes',unit:'kg',currentStock:4.2,reorderPoint:8,dailyUsage:2.8,unitCost:70,status:'Low',daysLeft:1.5,trend:'Falling'},{id:'spices',name:'Whole spices',unit:'kg',currentStock:1.8,reorderPoint:3,dailyUsage:2.2,unitCost:420,status:'Critical',daysLeft:.8,trend:'Falling'},{id:'paneer',name:'Paneer',unit:'kg',currentStock:12,reorderPoint:7,dailyUsage:4.2,unitCost:380,status:'Healthy',daysLeft:2.8,trend:'Stable'}]
export const stations:KitchenStation[]=[{id:'hot',name:'Hot kitchen',capacity:86,status:'Busy'},{id:'prep',name:'Prep station',capacity:72,status:'Ready'},{id:'bread',name:'Tandoor & breads',capacity:79,status:'Busy'}]
export const scenario:SimulationScenario={customerChange:0,weather:'Clear',holiday:'None',localEvent:'None',promotion:false}
export const alerts:Alert[]=[{id:'surge',title:'Demand surge detected',description:'Chicken Biryani demand is accelerating beyond the initial plan.',severity:'warning',dismissed:false,relatedEntity:'biryani'},{id:'spices',title:'Critical stock risk',description:'Whole spices are projected to reach critical stock in 0.8 days.',severity:'critical',dismissed:false,relatedEntity:'spices'}]
export const waste:WasteRecord[]=dishes.map((dish,i)=>({id:`waste-${dish.id}`,dishId:dish.id,prepared:dish.prepared,consumed:dish.actualOrders,spoilageKg:[1.2,.8,.7,.4,.5][i],overproductionKg:[7.2,4.3,4,2.4,3.1][i],wasteKg:dish.wasteKg,wasteCost:dish.wasteCost,date:'2025-06-24'}))
